Update main.py
Line https://github.com/ujsyehao/COCO-annotations-darknet-format/blob/9e6d20c63b9fc52ca557e0f41d40c2e111196e7c/main.py#L40 modified. 

Cause : TypeError: 'filter' object is not subscriptable

Try to modify by : 
- name = value1.next()['name']
- name = value1.first()['name']
Errors : AttributeError: 'filter' object has no attribute 'next' | 'first'

Success with : 
- name = value1.__next__()['name']